version: '3.8'

services:
  postgres:
    image: postgres:14-alpine3.16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: gofermart
    ports:
      - '5433:5432'
    volumes:
      - data:/var/lib/postgresql/data

  accrual:
    platform: linux/amd64
    build:
      dockerfile: .docker/accrual/Dockerfile
      context: ./
    environment:
      RUN_ADDRESS: "0.0.0.0:3001"
    ports:
      - "3001:3001"

volumes:
  data: